### ISSUE TITLE
Internal Link Duplication

### ISSUE THREAD

**Issue by JoeStratton** [andrewiankidd/Plextras.js#12]
Hi, great script!
When I use the "internal link" feature based off of your example:
**'Uptime':'javascript:internalLink("https://stats.uptimerobot.com/q7BGEHzZz")

It does load inside of Plex, but the issue is if I go back to another page it duplicates the links. This is endless it seems until the browser crashes.

See screenshot for example

http://imgur.com/a/X2zKr

**Comment by smoofus** [comment]
This happens to me as well.  I'm also having issues getting ombi to load inside of plex... it launches a new tab.

**Comment by andrewiankidd** [comment]
Sorry for the delay, fixed the iframe stuff - could you let me know if you see the link duplication again?

Thanks

https://github.com/andrewiankidd/Plextras.js/commit/f7f509e14c2bd3464afbbe6eeedb6f393685eb46

**Comment by JoeStratton** [comment]
Hi, sorry for my delay :) yes it is working perfectly. Thanks!
