### ISSUE TITLE
Custom links broken in Plex 1.8.0.4109 

### ISSUE THREAD

**Issue by ajkis** [andrewiankidd/Plextras.js#14]
Custom links got broken with latest plex update

**Comment by andrewiankidd** [comment]
https://github.com/andrewiankidd/Plextras.js/commit/412b1c465e08a8881fb74c4c421ca99af52c99f6

**Comment by andrewiankidd** [comment]
The new Plex UI has replaced all meaningful class names with obfuscated ID's, possibly in an effort to block things like Plextras working. I'll look into it some more and see what can be done

**Comment by andrewiankidd** [comment]
https://github.com/andrewiankidd/Plextras.js/commit/ec7022d5ddfa1e9cf2ec6cfc419cd142c6fab969

Let me know if this works for you please!

**Comment by ajkis** [comment]
It works again, thanks for quick response.
