### ISSUE TITLE
Custom links open within Plex

### ISSUE THREAD

**Issue by mattman86** [andrewiankidd/Plextras.js#4]
Is it possible to have the custom links open in the area where the library content is and keep the sidebar there? If not, just tell me to shut up and go ahead and close this issue.

**Comment by andrewiankidd** [comment]
I added an option for this, but it uses iframes and they dont work well with a lot of websites

this is what it looks like https://i.imgur.com/adLpuTI.png

to use it add your link like this
`'Uptime':'javascript:internalLink("https://stats.uptimerobot.com/q7BGEHzZz")'`
